version: '3.5'

networks:
  fiap-techchallenge:
    driver: bridge
    name: "fiap-techchallenge"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tech}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tech_passwd}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - fiap-techchallenge
    volumes:
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./src/main/resources/db/migrations/V0__create_schema.sql:/docker-entrypoint-initdb.d/V0__create_schema.sql
      - ./src/main/resources/db/migrations/V1__create_table_cliente.sql:/docker-entrypoint-initdb.d/V1__create_table_cliente.sql
      - ./src/main/resources/db/migrations/V2__create_table_produto.sql:/docker-entrypoint-initdb.d/V2__create_table_produto.sql
      - ./src/main/resources/db/migrations/V3__create_table_categoria.sql:/docker-entrypoint-initdb.d/V3__create_table_categoria.sql