services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tech}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tech_passwd}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - fiaptechchallengenetwork

  fiapfastfood:
    container_name: fiap-fast-food
    build:
      context: .
    image: fiap/fastfoodgrupo10
    ports:
      - "80:80"
    networks:
      - fiaptechchallengenetwork
    depends_on:
      - postgres

networks:
  fiaptechchallengenetwork:
    name: fiaptechchallengenetwork
    driver: bridge