version: '3.5'

networks:
  fiap-techchallenge:
    driver: bridge
    name: "fiap-techchallenge"

services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tech}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tech_passwd}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - fiap-techchallenge