spring:
  profiles:
    active: application
  application:
    name: tech-challenge
  datasource:
    url: jdbc:postgresql://postgres_container:5432/postgres
    username: tech
    password: tech_passwd
  jpa:
    properties:
      hibernate:
        default_schema: tech-challenge
        enable_lazy_load_no_trans: true
    show-sql: false
  flyway:
    schemas: tech-challenge
  data:
    web:
      pageable:
        one-indexed-parameters: true

server:
  servlet:
    context-path: /api
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
  path: swagger-ui-custom.html

