spring:
  profiles:
    active: application

  application:
    name: tech-challenge

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: tech
    password: tech_passwd
  jpa:
    properties:
      hibernate:
        default_schema: tech-challenge
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    show-sql: true

server:
  servlet:
    context-path: /api
  port: 9002

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
  path: swagger-ui-custom.html

